steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/container1-repo/container1:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/container1-repo/container1:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['container', 'clusters', 'get-credentials', 'my-gke-cluster', '--zone', 'us-central1-a', '--project', '$PROJECT_ID']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/container1-deployment', 'container1=us-central1-docker.pkg.dev/$PROJECT_ID/container1-repo/container1:$COMMIT_SHA']
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/container1-repo/container1:$COMMIT_SHA'